[package]
name = "hello_macro_derive"
version = "0.1.0"
authors = ["liuboheng <lbh9311@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.16"
quote = "1.0.3"

[lib]
proc-macro = true